[package]
name = "delta-synth"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.24.0"
eframe = "0.27"
midir = "0.9"
image = "0.24.9"
rand = "0.9.2"
winit = "0.28"
pixels = "0.12"
log = "0.4"
env_logger = "0.10"